# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GwDrive < Formula
  desc "Read-only Google Workspace Drive CLI and MCP server"
  homepage "https://github.com/spandigital/gw-drive-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.0/gw-drive_0.1.0_darwin_amd64.tar.gz"
      sha256 "58498ea12e4a810b05605a05100074081db38a466ace5d711aa3e91894664ade"

      define_method(:install) do
        bin.install "gw-drive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.0/gw-drive_0.1.0_darwin_arm64.tar.gz"
      sha256 "8fd0d8f0e468d52a435b4f90d3e817ff44e6dfc001f0f25b5970b5aa2b0c0967"

      define_method(:install) do
        bin.install "gw-drive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.0/gw-drive_0.1.0_linux_amd64.tar.gz"
      sha256 "ec69da95d5f933dcc7e2b30a121ba9e2bb61f5fead77ae63c28e3456b0c70e1b"
      define_method(:install) do
        bin.install "gw-drive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.0/gw-drive_0.1.0_linux_arm64.tar.gz"
      sha256 "d4450f2bdfca2e4397497673ab13b5e55b4301c78e68e38d4c07579b572985fc"
      define_method(:install) do
        bin.install "gw-drive"
      end
    end
  end

  test do
    system "#{bin}/gw-drive", "--version"
  end
end
