# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Presidium < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "1.0.0-rfv.218"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.218/presidium-hugo_1.0.0-rfv.218_Darwin_arm64.tar.gz"
      sha256 "88bdec03ca3dc6d9ba9eb7a6092368ccbd307a025219b00f27da75889009e122"

      def install
        bin.install "presidium-hugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.218/presidium-hugo_1.0.0-rfv.218_Darwin_x86_64.tar.gz"
      sha256 "5a273dc9af8821ecf0745749f4da73200bc478177d6a865607ffd584d2971e37"

      def install
        bin.install "presidium-hugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.218/presidium-hugo_1.0.0-rfv.218_Linux_arm64.tar.gz"
      sha256 "27928744efe0ae0c35fa854551e4c5dfdc122639fba7f8ae97d19137e198fbbd"

      def install
        bin.install "presidium-hugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.218/presidium-hugo_1.0.0-rfv.218_Linux_x86_64.tar.gz"
      sha256 "06866cb9f9c2759c8722a79523f64b93086b81370c0786547c360d59659bdea4"

      def install
        bin.install "presidium-hugo"
      end
    end
  end
end
