# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rst2md < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.6/presidium-rst-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "ab9e8fd4e0c8ec30c13234132697333bc76b28d8bb35b2e8409fbf26dbf6979a"

      def install
        bin.install "rst2md"
      end
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.6/presidium-rst-to-markdown_Darwin_arm64.tar.gz"
      sha256 "8022d39d32c53c8947d96ab0f4d488a6f2f6288c18bd94d4db0df540597557ab"

      def install
        bin.install "rst2md"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.6/presidium-rst-to-markdown_Linux_x86_64.tar.gz"
        sha256 "b9150e7fd701ae29f42591b35bb9b6f2a62bcde83d996be90c63ff1b0d070fb1"

        def install
          bin.install "rst2md"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.6/presidium-rst-to-markdown_Linux_arm64.tar.gz"
        sha256 "cb4040fe8d0ddd441b5a9bbd94434298cbcd47a32aa42a1bf781237a47521ff9"

        def install
          bin.install "rst2md"
        end
      end
    end
  end
end
