# This file was generated by GoReleaser. DO NOT EDIT.
cask "presidium" do
  version "2.0.0-rfv.19"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Darwin_x86_64.tar.gz"
      sha256 "1920d8a864d7b1fc4ef26d3e178a03d133768262e43b83ba4cf2eee2a557aa64"
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Darwin_arm64.tar.gz"
      sha256 "0bbdf12ea58c2a583062368b7490f758699d08477422f10effddea406f69a09f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Linux_x86_64.tar.gz"
      sha256 "c2d4668a2e5144a02e2480bfde199dc60adc18221ec99b925500fa3d3e205217"
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Linux_arm64.tar.gz"
      sha256 "c47ae4a524494fb723bd13470ac3f51187238a96e7dc219d1caa04dbee7bd2cb"
    end
  end

  name "presidium"
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "presidium"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/presidium"]
    end
  end

  # No zap stanza required

end
