# This file was generated by GoReleaser. DO NOT EDIT.
cask "presidium" do
  version "2.1.0"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Darwin_x86_64.tar.gz"
      sha256 "17899a6fbbecb93aaf424180a3e0dcf8e4f56b07c3dc25a663cfcbc83d1225ab"
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Darwin_arm64.tar.gz"
      sha256 "0ad9d7e98c11671301624f1bb5778ecf3596346709093cd2b299fcef04a42e1c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Linux_x86_64.tar.gz"
      sha256 "209931015c01098adc0e11fd0ba78a98ce802fcb9d722dad7041c0100ef236dc"
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Linux_arm64.tar.gz"
      sha256 "4af18aa13f00b7f1dadf58fa24f72f4673c199dcab0938c482c4806c772d2a95"
    end
  end

  name "presidium"
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "presidium"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/presidium"]
    end
  end

  # No zap stanza required

end
