# This file was generated by GoReleaser. DO NOT EDIT.
cask "presidium" do
  version "2.1.1"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Darwin_x86_64.tar.gz"
      sha256 "ea14cd7707b4614360406be3f7b62d03cefb701f5b16d4365c4d838fbb309146"
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Darwin_arm64.tar.gz"
      sha256 "720785e2b76b3af46eba9be1fe7cdf656591618917e2b1418d574f316069cad1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Linux_x86_64.tar.gz"
      sha256 "bfc79371b17decef957530f9130591dc050daf03081151e78bf42b483f38c4b4"
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium/releases/download/v#{version}/presidium_Linux_arm64.tar.gz"
      sha256 "1eaf410c94c1e51958bfe5011782c61ade54737cb19334103b626e90d7f5ee34"
    end
  end

  name "presidium"
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "presidium"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/presidium"]
    end
  end

  # No zap stanza required

end
