# This file was generated by GoReleaser. DO NOT EDIT.
cask "token-visualizer" do
  name "token-visualizer"
  desc "Modern CLI tool for visualizing and analyzing LLM tokens"
  homepage "https://github.com/SPANDigital/token-visualizer"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "token-visualizer"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Darwin_x86_64.tar.gz"
      sha256 "86f3489fa24b21e4e8e4cb6978b7be6ceb546721f5e12eff038f9c753bb31ac9"
    end
    on_arm do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Darwin_arm64.tar.gz"
      sha256 "932a10934aa4ab8325fcddf0a5940673c7a95fd2f1e8d760a69dece392967e5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Linux_x86_64.tar.gz"
      sha256 "50463acf6892017d8b4c11a07a01f542799f7991e2a9fb679454afd42472017f"
    end
    on_arm do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Linux_arm64.tar.gz"
      sha256 "11045f0fbca9a26d03ebbc64809a0156535652fc77aa54e99ea32d2f52670ba5"
    end
  end

  # No zap stanza required
end
