# This file was generated by GoReleaser. DO NOT EDIT.
cask "token-visualizer" do
  name "token-visualizer"
  desc "Modern CLI tool for visualizing and analyzing LLM tokens"
  homepage "https://github.com/SPANDigital/token-visualizer"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "token-visualizer"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Darwin_x86_64.tar.gz"
      sha256 "e2dc074025a3db3a5c9abb654ce0466485269eb102a3325c8d090ef7d860d5c5"
    end
    on_arm do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Darwin_arm64.tar.gz"
      sha256 "36ab36b567cab0c4216e44a6c7917e04e77d57cb3c4329be0c7c1916b6e13c5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Linux_x86_64.tar.gz"
      sha256 "19194e6c573ccc53a3a70cc904c1aaa8baab4cd2c9257cce81fef2369b6c0d0b"
    end
    on_arm do
      url "https://github.com/SPANDigital/token-visualizer/releases/download/v#{version}/token-visualizer_#{version}_Linux_arm64.tar.gz"
      sha256 "1bce38010816cbda5e41469143bf672e1fafc85eb0b288d66fe7347cca44a3b8"
    end
  end

  # No zap stanza required
end
