# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codassistant < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/SPANDigital/codeassistant"
  version "0.1.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v0.1.10/codeassistant_Darwin_arm64.tar.gz""
      sha256 "5307ee96213a7a7f4bd26f96ba426048402c6b3388c53e2627750acdb15311ff"

      def install
        bin.install "codeassistant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v0.1.10/codeassistant_Darwin_x86_64.tar.gz""
      sha256 "b5a77cc97f2b98e735cbd274e3a29888045ca0ab49bfbc47c366b9b5493f4a48"

      def install
        bin.install "codeassistant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v0.1.10/codeassistant_Linux_arm64.tar.gz""
      sha256 "4e4bb660f12d58712612d9e3e00b641c6af9b9bc3fa0c98fb502aa2d153b56b8"

      def install
        bin.install "codeassistant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v0.1.10/codeassistant_Linux_x86_64.tar.gz""
      sha256 "e06fb7e7bd611365763d6aa4a7469b4c864f390ae5742cdf2381420bc35d1f49"

      def install
        bin.install "codeassistant"
      end
    end
  end
end
