# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeblocks < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/SPANDigital/codeblocks"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/codeblocks/releases/download/v0.0.5/codeblocks_Darwin_arm64.tar.gz"
      sha256 "af807a88a93407731d0a8c6ebda6196c88cd25cfe730dbad3fb64923719a7321"

      def install
        bin.install "codeblocks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/codeblocks/releases/download/v0.0.5/codeblocks_Darwin_x86_64.tar.gz"
      sha256 "bbdb02810e73a45e960e6becfe2d1a0beaf4749d41b451d4cb1d7b6457348c0f"

      def install
        bin.install "codeblocks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/codeblocks/releases/download/v0.0.5/codeblocks_Linux_arm64.tar.gz"
      sha256 "e45569a728b0d1e551f593af86de59be80d7214a80bf7eb3136a6c77f4d77141"

      def install
        bin.install "codeblocks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/codeblocks/releases/download/v0.0.5/codeblocks_Linux_x86_64.tar.gz"
      sha256 "e9b11e109448b8401452eaeb8fa24f7daf3aa44133da7ac6b7b8db52b872818d"

      def install
        bin.install "codeblocks"
      end
    end
  end
end
