# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeassistant < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/SPANDigital/codeassistant"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v2.0.1/codeassistant_Darwin_x86_64.tar.gz"
      sha256 "6b9435ccd22430954454162e1f28f433e7db9caac330f2109b298a6a99a2ccb7"

      def install
        bin.install "codeassistant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v2.0.1/codeassistant_Darwin_arm64.tar.gz"
      sha256 "928e3deda969ce1196c11aa15390956adf2aeafb8ad0d6060e1f7c2d0f3e5232"

      def install
        bin.install "codeassistant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v2.0.1/codeassistant_Linux_arm64.tar.gz"
      sha256 "454d78b5c70eb6f8bbcacd06e293c52d423a7b2ff8f6aa4e2141d069ea6c75f9"

      def install
        bin.install "codeassistant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/codeassistant/releases/download/v2.0.1/codeassistant_Linux_x86_64.tar.gz"
      sha256 "e50652f4a50dc38f6a7b1d24fde77331eeb97902f56f40b39f923d816728cc11"

      def install
        bin.install "codeassistant"
      end
    end
  end
end
