# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class GwDrive < Formula
  desc "Read-only Google Workspace Drive CLI and MCP server"
  homepage "https://github.com/spandigital/gw-drive-cli"
  version "0.1.26"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.26/gw-drive_0.1.26_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ef1632552d1a1d28beafb8ea1e2b5a73210aa0feacbb6138fb8dd196a7051e8c"

      define_method(:install) do
        bin.install "gw-drive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.26/gw-drive_0.1.26_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2483966ee76aaf560e382e1d28abee3794cbd80972716e9e3c749788af01dd2f"

      define_method(:install) do
        bin.install "gw-drive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.26/gw-drive_0.1.26_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1570242d844341399d3752c2bab6e37ffbf78901ac0cc96c36df9fc11dd54251"
      define_method(:install) do
        bin.install "gw-drive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spandigital/gw-drive-cli/releases/download/v0.1.26/gw-drive_0.1.26_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1d77775da6c69ebb5390b563790421bec8de1d1e8ac89bb1c782f397bc6df66f"
      define_method(:install) do
        bin.install "gw-drive"
      end
    end
  end

  test do
    system "#{bin}/gw-drive", "--version"
  end
end
