# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Html2md < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "0.0.1-develop.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.1-develop.2/presidium-html-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "763989eefe8256766d1aa121be15ed78b4697334c8463f732d2274c3361edb85"

      def install
        bin.install "presidium-html-to-markdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.1-develop.2/presidium-html-to-markdown_Darwin_arm64.tar.gz"
      sha256 "43234f70f27ab76c6ef7e7e47dec42cb98b28795a48937a90aa0416db1daaecd"

      def install
        bin.install "presidium-html-to-markdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.1-develop.2/presidium-html-to-markdown_Linux_arm64.tar.gz"
      sha256 "628749adc6499b59af4c203f22163f5ec8946133ec4427487d8597a89bc9a90c"

      def install
        bin.install "presidium-html-to-markdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.1-develop.2/presidium-html-to-markdown_Linux_x86_64.tar.gz"
      sha256 "fee922c8c85dfd67a8ef4a8937b311407ec0ef5515cef6e310c58c961c89a7ad"

      def install
        bin.install "presidium-html-to-markdown"
      end
    end
  end
end
