# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Html2md < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/SPANDigital/presidium-html-to-markdown"
  version "0.0.4-develop.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.4-develop.0/presidium-html-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "41daf7322fb073b589c7aeba02e339b203b02aafbd249671c38a538b05ef24da"

      def install
        bin.install "html2md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.4-develop.0/presidium-html-to-markdown_Darwin_arm64.tar.gz"
      sha256 "65e18f6645bc5dd274798e56d216fcf11daf7afc4e816a13a1f9d0059b3b96dd"

      def install
        bin.install "html2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.4-develop.0/presidium-html-to-markdown_Linux_arm64.tar.gz"
      sha256 "c62f5168e28b8b8fa73b6bea913cd2f62c8aa09ceedbd026deb538dcfdd53216"

      def install
        bin.install "html2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-html-to-markdown/releases/download/v0.0.4-develop.0/presidium-html-to-markdown_Linux_x86_64.tar.gz"
      sha256 "3046fa440c88c1d927342890805dde3aab4522f8c117db00bcd529f064b394f7"

      def install
        bin.install "html2md"
      end
    end
  end
end
