# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpServerDump < Formula
  desc "Extract and document MCP server capabilities in various formats"
  homepage "https://github.com/spandigital/mcp-server-dump"
  version "1.34.1"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/mcp-server-dump/releases/download/v1.34.1/mcp-server-dump_Darwin_x86_64.tar.gz"
      sha256 "e345756c6a6325f7302df544e5818331c81ee6ea0e1f43ba46ce6b85e620f0fd"

      def install
        bin.install "mcp-server-dump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/mcp-server-dump/releases/download/v1.34.1/mcp-server-dump_Darwin_arm64.tar.gz"
      sha256 "2cb8a7c4a04b67cd459a2c654582591cb59363c8a734c4b48184bafdce11c654"

      def install
        bin.install "mcp-server-dump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/mcp-server-dump/releases/download/v1.34.1/mcp-server-dump_Linux_x86_64.tar.gz"
      sha256 "479c37b1971e258c67d321cf919d721f05938bb7dbdee6e9bdc748bddd926298"
      def install
        bin.install "mcp-server-dump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/mcp-server-dump/releases/download/v1.34.1/mcp-server-dump_Linux_arm64.tar.gz"
      sha256 "c4956d04206f5609cd825345dd3d1bfabc3b77a2f473254bdadd7083ba4a57fb"
      def install
        bin.install "mcp-server-dump"
      end
    end
  end

  test do
    system "#{bin}/mcp-server-dump", "--help"
  end
end
