# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PresidiumJsonSchema < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.6/presidium-json-schema_Darwin_x86_64.tar.gz"
      sha256 "2b35d5d92556451e1bb7860fc737878d8e34528f2fbffc91b11b5f011527c23a"

      def install
        bin.install "presidium-json-schema"
      end
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.6/presidium-json-schema_Darwin_arm64.tar.gz"
      sha256 "29e764cdd392a65928eee94c9b93d8c536c0e1a1d3d2e3fc93c283d1aa14d842"

      def install
        bin.install "presidium-json-schema"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.6/presidium-json-schema_Linux_x86_64.tar.gz"
        sha256 "e009048380600ac826f7981aba70c5161a78d5263c6b2921fb548ecf546de3bc"

        def install
          bin.install "presidium-json-schema"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.6/presidium-json-schema_Linux_arm64.tar.gz"
        sha256 "5842d98cf5631d0f8855050cf4824e9177cc13a169c05927aacc695090090394"

        def install
          bin.install "presidium-json-schema"
        end
      end
    end
  end
end
