# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PresidiumJsonSchema < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.1/presidium-json-schema_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6a318a0870e00b657b413df65072ec93c4328e0a1e667234c0a63e9575fd0006"

      def install
        bin.install "presidium-json-schema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.1/presidium-json-schema_0.1.1_Darwin_arm64.tar.gz"
      sha256 "1ca80c46a5980326d2f69a52d36d3e470ce85beefb856e5de10ef503fed6d12b"

      def install
        bin.install "presidium-json-schema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.1/presidium-json-schema_0.1.1_Linux_arm64.tar.gz"
      sha256 "3d8430e9bf139c0851140a26e6db8471fc1413699815023a86bd929fe151ecc7"

      def install
        bin.install "presidium-json-schema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-json-schema/releases/download/v0.1.1/presidium-json-schema_0.1.1_Linux_x86_64.tar.gz"
      sha256 "168257c983a428a70b103ed55a5da46b79807444d5a6629eb113a16a9284aead"

      def install
        bin.install "presidium-json-schema"
      end
    end
  end
end
