# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Presidium < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "1.0.0-rfv.246"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium/releases/download/v1.0.0-rfv.246/presidium_1.0.0-rfv.246_Darwin_arm64.tar.gz"
      sha256 "54f2a81f2e9bc95a71a3607ebb85921f176745ac46aa4d413ea42d6e89497b40"

      def install
        bin.install "presidium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium/releases/download/v1.0.0-rfv.246/presidium_1.0.0-rfv.246_Darwin_x86_64.tar.gz"
      sha256 "845b3dbce8e5e670412db20ad02755cf85dde8b05f21fdc458e6c83823890e50"

      def install
        bin.install "presidium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium/releases/download/v1.0.0-rfv.246/presidium_1.0.0-rfv.246_Linux_x86_64.tar.gz"
      sha256 "c76ea4a71a2dcc1ba54f917b1ddd9bf2b270198570eef08940eb8ca86c295766"

      def install
        bin.install "presidium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium/releases/download/v1.0.0-rfv.246/presidium_1.0.0-rfv.246_Linux_arm64.tar.gz"
      sha256 "293e34cbad57954cc445307c89176625cac39e5f33c5615b25761c73b6d35a3b"

      def install
        bin.install "presidium"
      end
    end
  end
end
