# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PresidiumPresidiumOapi3 < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "2.11.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-oapi3/releases/download/v2.11.1/presidium-oapi3_Darwin_x86_64.tar.gz"
      sha256 "d9223f54fa6affd94bad11d29d41e7431ea88cfa9862fff6f54b55f5af524acf"

      def install
        bin.install "presidium-oapi3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-oapi3/releases/download/v2.11.1/presidium-oapi3_Darwin_arm64.tar.gz"
      sha256 "76e1ebed13b6e3d88ec653e65865eabf4fb1189056115c454c0a8cddb7891a8d"

      def install
        bin.install "presidium-oapi3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-oapi3/releases/download/v2.11.1/presidium-oapi3_Linux_arm64.tar.gz"
      sha256 "c2c31202b555de957930e43f78f9fbbdf516422624b7039d978579309e740d0b"

      def install
        bin.install "presidium-oapi3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-oapi3/releases/download/v2.11.1/presidium-oapi3_Linux_x86_64.tar.gz"
      sha256 "ba48f95865f00ee74df4207e56424435576e9a04666029b0933f8f0f3f408ab0"

      def install
        bin.install "presidium-oapi3"
      end
    end
  end
end
