# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Presidium < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "1.0.0-rfv.221"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.221/presidium-hugo_1.0.0-rfv.221_Darwin_arm64.tar.gz"
      sha256 "5c8c9f1e66ee0bbd893391d66113e30798a953c083c31926b29eea8b676b33b6"

      def install
        bin.install "presidium-hugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.221/presidium-hugo_1.0.0-rfv.221_Darwin_x86_64.tar.gz"
      sha256 "35da6e844da34aedfbced175a55d4fdf4aed17403ca55c2932717128fa374bba"

      def install
        bin.install "presidium-hugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.221/presidium-hugo_1.0.0-rfv.221_Linux_arm64.tar.gz"
      sha256 "871985cd1434fba31d246139abfe35f5c284d26ca21e26ac0cedcc8394884a08"

      def install
        bin.install "presidium-hugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.221/presidium-hugo_1.0.0-rfv.221_Linux_x86_64.tar.gz"
      sha256 "71059c10dfbaffa5c8fccb0eec94136106f19f291a78367248fff385035d6da7"

      def install
        bin.install "presidium-hugo"
      end
    end
  end
end
