# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Presidium < Formula
  desc "Presidium is a software documentation management system for agile teams"
  homepage "https://github.com/spandigital/presidium"
  version "1.0.0-rfv.222"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.222/presidium-hugo_1.0.0-rfv.222_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9353e4d14b169d846a735faab1797365cafe04e0150f755129648ff91f2f3286"

      def install
        bin.install "presidium-hugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.222/presidium-hugo_1.0.0-rfv.222_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2b0c3ec8867db17e74dab028540940b5c8c72baad3bb4be060c48ea7b85bc2f8"

      def install
        bin.install "presidium-hugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.222/presidium-hugo_1.0.0-rfv.222_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cb3ab893a729fcd026d912a3fc750cfd3e26e2b05b14f84a38feaf97ce41afb2"

      def install
        bin.install "presidium-hugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/presidium-hugo/releases/download/v1.0.0-rfv.222/presidium-hugo_1.0.0-rfv.222_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9f28d03fb52768970db4447db66dbf2f5dd428e05490206fdc008cb6ab9da2fe"

      def install
        bin.install "presidium-hugo"
      end
    end
  end
end
