# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rst2md < Formula
  desc ""
  homepage ""
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.7/presidium-rst-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "3044b3d75f96a59449050af17bfef282b19afcab6296e3d5ccfa66140e2d8739"

      def install
        bin.install "rst2md"
      end
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.7/presidium-rst-to-markdown_Darwin_arm64.tar.gz"
      sha256 "6a571e82b8d4f61c24b0f01a3891096094d02d5bdde6615463b78ef34a6ff158"

      def install
        bin.install "rst2md"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.7/presidium-rst-to-markdown_Linux_x86_64.tar.gz"
        sha256 "6d3e392a4b4af96582ebc145a2d00aaec794afdd2c67e74e01e686109d50f5f0"

        def install
          bin.install "rst2md"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.0.7/presidium-rst-to-markdown_Linux_arm64.tar.gz"
        sha256 "f7ec92dd93d8ba1a66dea72982d2c7ab10cdd63235415d8e82d6388957c4c51c"

        def install
          bin.install "rst2md"
        end
      end
    end
  end
end
