# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rst2md < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.1.0/presidium-rst-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "e6f6567bd258a392851554f9144704c97b0398878a92114886458470349645d1"

      def install
        bin.install "rst2md"
      end
    end
    on_arm do
      url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.1.0/presidium-rst-to-markdown_Darwin_arm64.tar.gz"
      sha256 "c9f06365b6a87ad00cb7b5ecd5190fbb49978e7ee81d65307354d3006258a7b2"

      def install
        bin.install "rst2md"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.1.0/presidium-rst-to-markdown_Linux_x86_64.tar.gz"
        sha256 "b18b8dcc071a0d87dc571dab1b3493aaa5c04c42524f241b2cdaeaaff901316c"

        def install
          bin.install "rst2md"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SPANDigital/presidium-rst-to-markdown/releases/download/v0.1.0/presidium-rst-to-markdown_Linux_arm64.tar.gz"
        sha256 "00f1da1ced1f375dd4f66948b5595a2fe1995044945122d4552bdbf0d62aabd7"

        def install
          bin.install "rst2md"
        end
      end
    end
  end
end
