# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class SpanOps < Formula
  desc "span-ops allows you to interact with the supplier services that SPAN uses."
  homepage "https://github.com/SPANDigital/span-ops"
  version "0.1.12"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.12/span-ops_0.1.12_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "145782779c12e5a9f8546c8811a495aa29d381cbed1b6c282457a224677f884b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.12/span-ops_0.1.12_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9c827fbd376579dc04c0d19578e5728e738568aa250ec5e5ee8d0d5166e79cf5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.12/span-ops_0.1.12_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1ac54daf16db38fbe7d04939f7b03dbf533c8007ba099db5e5e49a942f11b584"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.12/span-ops_0.1.12_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c938c1208b37ceafbd9f75d8cf3273310d3f3963bdd645bc0083272e551ca3b1"
    end
  end

  def install
    bin.install "span-ops"
  end
end
