# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpanOps < Formula
  desc "span-ops allows you to interact with the supplier services that SPAN uses."
  homepage "https://github.com/SPANDigital/span-ops"
  version "0.1.10"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.10/span-ops_0.1.10_Darwin_x86_64.tar.gz"
      sha256 "f694e8edd675e66f9d22a3d180daeabeb396ef58121d966e033d06f18b826045"
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.10/span-ops_0.1.10_Darwin_arm64.tar.gz"
      sha256 "58d2f64c6aa43f47390347a19baf7c12b29dedd1df789434b620e2691a6ad0b5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.10/span-ops_0.1.10_Linux_x86_64.tar.gz"
      sha256 "8405e3cd5031771184b9888d485284d1f5f91b574e6ef5bd679e7c3cf6dc67e3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPANDigital/span-ops/releases/download/v0.1.10/span-ops_0.1.10_Linux_arm64.tar.gz"
      sha256 "8c3e8d6e01954648b3c01ab15430ab5c718b8cb539c15f15a91d23bad2fb1edb"
    end
  end

  def install
    bin.install "span-ops"
  end
end
